# Generated by Django 2.2 on 2020-07-23 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date',
            field=models.CharField(default=None, max_length=11, null=True, verbose_name='Дата выполнения (ГГГГ-ММ-ДД)'),
        ),
    ]
