# Generated by Django 2.2 on 2020-07-23 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20200723_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date',
            field=models.DateField(default=None, null=True, verbose_name='Дата выполнения (ГГГГ-ММ-ДД)'),
        ),
    ]
