# Generated by Django 2.2 on 2020-07-26 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20200723_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='more',
            field=models.TextField(max_length=1500, null=True, verbose_name='Более подробное описание задачи'),
        ),
    ]
